# Generated by Django 5.2.3 on 2025-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFileView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField()),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('uploader', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'public_file_view',
                'managed': False,
            },
        ),
    ]
