# Generated by Django 5.2.3 on 2025-06-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_publicfileview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicFileView',
        ),
    ]
